config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "lists#index"
  resources :lists, only: [:index, :show, :new, :create, :destroy] do
    resources :bookmarks, only: [:new, :create]
    resources :reviews, only: [:create]

  end
  resources :bookmarks, only: [:destroy]
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, presence: true, length: { minimum: 6, message: "Check it, might be more or less than 6" }
  # validates_uniqueness_of :movie_id, scope: :list_id
  # validates :movie, presence: true, uniqueness: {scope: :list}
  validates :movie_id, presence: true, uniqueness: {scope: :list_id, message: 'is already in the list'}
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true
  has_many :bookmarks
  has_many :reviews,  dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, uniqueness: true, presence: true
  validates :overview, uniqueness: true, presence: true
  has_many :bookmarks
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
  validates :content, presence: true
  # Only integer
  validates :rating, numericality: {only_integer: true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    # this bookmark is owned by this list now
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list), notice: "List was successfully created."
    else
      render 'lists/show', status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show destroy]
  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
    @review = Review.new
  end

# Empty instance just to send to rails to say what the form needs to do
  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list.id), notice: "List was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def list_params
    params.require(:list).permit(:name, :photo)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @review = Review.new(review_params)
    @list = List.find(params[:list_id])
    @review.list = @list
    if @review.save
      redirect_to list_path(@list)
    else
      @bookmark = Bookmark.new
      render 'lists/show', status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to list_path(@review.list)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/create.html.erb
<h1>Bookmarks#create</h1>
<p>Find me in app/views/bookmarks/create.html.erb</p>

app/views/bookmarks/destroy.html.erb
<h1>Bookmarks#destroy</h1>
<p>Find me in app/views/bookmarks/destroy.html.erb</p>

app/views/bookmarks/new.html.erb
<h1>Bookmarks#new</h1>
<p>Find me in app/views/bookmarks/new.html.erb</p>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.submit "create" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>All lists</h1>
<%= link_to "make a new list", new_list_path %>
<ul>
  <% @lists.each do |list| %>
  <% if list.photo.attached? %>
    <%= cl_image_tag(list.photo.key, width: 400, height: 300, crop: :fill) %>
  <% end %>
    <li><%= link_to "See details of: #{list.name}", list_path(list) %> <%= button_to "delete it", list_path(list), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></li>
<% end %>
</ul>

app/views/lists/new.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit %>
<% end %>

app/views/lists/show.html.erb
      <h1><%= @list.name %></h1>
      <table class="table table-bordered">
        <tbody>
          <tr>
            <th scope="row">Name</th>
            <td><%= @list.name %></td>
          </tr>

        </tbody>
      </table>



      <%= link_to "See all lists", lists_path %>

    <div class="container">
      <div class="row">
        <%  @list.movies.each do |movie| %>
        <div class="col">
            <% @new_bookmark = Bookmark.find_by(list: @list, movie: movie) %>
            <div class="row"><strong><%= movie.title%></strong></div>
            <div class="row"><img src="<%= movie.poster_url%>" class="rounded float-start" alt="<%= movie.title%>"></div>
            <div class="row"><strong>Overview: </strong><%= movie.overview%></div>
            <div class="row"><strong>My Comments: </strong><%= @new_bookmark.comment%> </div>
            <div class="row"> <strong>Rating: </strong><%= movie.rating%>
            <strong><%= link_to "Delete",  bookmark_path(@new_bookmark),  data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to remove #{movie.title} from your #{@list.name} list"}%></strong></div>
         </div>
        <% end %>
      </div>

    <div class="container">
      <div class="row">
        <h3><strong>Reviews</strong></h3>
        <%  @list.reviews.each do |review| %>
        <div class="col">

            <li class="list-group-item">
            <small>
              <% count = 0 %>
              <% 5.times do %>
                <% if review.rating > count %>
                  <i class="fa-solid fa-star"></i>
                <% else %>
                  <i class="fa-regular fa-star"></i>
                <% end %>
                <% count += 1 %>
              <% end %>
            </small>
            <p><%= review.content %></p>

            <strong><%= link_to "Delete",  review_path(review),  data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this review?"}%></strong></div>
</li>
         </div>
        <% end %>
      </div>
      <h2>Add a movie</h2>
      <%= simple_form_for [@list,@bookmark] do |f| %>
        <%= f.input :movie_id, collection: Movie.order('title')%>
        <%= f.input :comment %>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>

      <h2>Add a review</h2>
      <%= simple_form_for [@list,@review] do |f| %>
        <%= f.input :rating, collection: 0..5 %>
        <%= f.input :content %>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>